# Generated by Django 6.0 on 2025-12-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_otp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="otp",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="otp",
            name="accounts_ot_user_id_844282_idx",
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="otp",
            index=models.Index(
                fields=["user", "purpose", "channel", "-created_at"],
                name="accounts_ot_user_id_4286c7_idx",
            ),
        ),
    ]
